import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import listingsRouter from "./listings";
import ordersRouter from "./orders";
import diseaseRouter from "./disease";
import livestockDiseaseRouter from "./livestock-disease";
import pricesRouter from "./prices";
import dashboardRouter from "./dashboard";
import uploadRouter from "./upload";
import farmersRouter from "./farmers";
import messagesRouter from "./messages";
import subscriptionRouter from "./subscription";
import sponsorsRouter from "./sponsors";
import paymentsRouter from "./payments";
import reviewsRouter from "./reviews";
import webhooksRouter from "./webhooks";
import setupRouter from "./setup";
import disputesRouter from "./disputes";
import withdrawalsRouter from "./withdrawals";
import transactionsRouter from "./transactions";
import notificationsRouter from "./notifications";
import reportsRouter from "./reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(setupRouter);
router.use(authRouter);
router.use(listingsRouter);
router.use(ordersRouter);
router.use(diseaseRouter);
router.use(livestockDiseaseRouter);
router.use(pricesRouter);
router.use(dashboardRouter);
router.use(uploadRouter);
router.use(farmersRouter);
router.use(messagesRouter);
router.use(subscriptionRouter);
router.use(sponsorsRouter);
router.use(paymentsRouter);
router.use(reviewsRouter);
router.use(webhooksRouter);
router.use(disputesRouter);
router.use(withdrawalsRouter);
router.use(transactionsRouter);
router.use(notificationsRouter);
router.use(reportsRouter);

export default router;
